"""TDD for taintrace — typosquat detector for AI agent dependencies."""

import pytest
from taintrace.lockfile import LockfileParser, Dependency
from taintrace.similarity import SimilarityEngine
from taintrace.scorer import RiskScorer, RiskLevel
from taintrace.db import KnownPackagesDB


# ── Lockfile Parser Tests ───────────────────────────────────────────

class TestCargoLockParser:
    """Parse Cargo.lock files and extract dependency names."""

    def test_parse_simple_cargo_lock(self, tmp_path):
        """Extracts package names from a basic Cargo.lock."""
        cargo_lock = tmp_path / "Cargo.lock"
        cargo_lock.write_text("""# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.204"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.38.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "proc-macro1"
version = "1.0.107"
source = "registry+https://github.com/rust-lang/crates.io-index"
""")
        parser = LockfileParser()
        deps = parser.parse(cargo_lock)
        names = [d.name for d in deps]
        assert "serde" in names
        assert "tokio" in names
        assert "proc-macro1" in names
        assert len(deps) == 3

    def test_parse_cargo_lock_with_duplicates(self, tmp_path):
        """Handles multiple versions of the same package."""
        cargo_lock = tmp_path / "Cargo.lock"
        cargo_lock.write_text("""version = 3

[[package]]
name = "serde"
version = "1.0.204"

[[package]]
name = "serde"
version = "1.0.203"

[[package]]
name = "tokio"
version = "1.38.0"
""")
        parser = LockfileParser()
        deps = parser.parse(cargo_lock)
        names = [d.name for d in deps]
        # Should include both serde entries (different versions)
        assert names.count("serde") == 2
        assert "tokio" in names

    def test_parse_empty_cargo_lock(self, tmp_path):
        """Handles empty or malformed lockfile gracefully."""
        cargo_lock = tmp_path / "Cargo.lock"
        cargo_lock.write_text("version = 3\n")
        parser = LockfileParser()
        deps = parser.parse(cargo_lock)
        assert len(deps) == 0

    def test_dependency_dataclass(self):
        """Dependency dataclass holds name and version."""
        dep = Dependency(name="serde", version="1.0.204", ecosystem="rust")
        assert dep.name == "serde"
        assert dep.version == "1.0.204"
        assert dep.ecosystem == "rust"


# ── Similarity Engine Tests ────────────────────────────────────────

class TestSimilarityEngine:
    """Calculate similarity between package names."""

    def test_identical_names(self):
        engine = SimilarityEngine()
        score = engine.similarity("serde", "serde")
        assert score == 1.0

    def test_completely_different(self):
        engine = SimilarityEngine()
        score = engine.similarity("abc", "xyz")
        assert score < 0.5

    def test_typosquat_proc_macro1_vs_proc_macro2(self):
        """The arrayref attack vector: proc-macro1 vs proc-macro2."""
        engine = SimilarityEngine()
        score = engine.similarity("proc-macro1", "proc-macro2")
        # Should be very high (only one char difference)
        assert score > 0.9

    def test_typosquat_arrayref_vs_arrayvec(self):
        """arrayref vs arrayvec — similar names, different packages."""
        engine = SimilarityEngine()
        score = engine.similarity("arrayref", "arrayvec")
        assert score > 0.5

    def test_single_digit_suffix(self):
        """Packages with single digit suffix (lodash vs lodash1)."""
        engine = SimilarityEngine()
        score = engine.similarity("lodash", "lodash1")
        assert score > 0.8

    def test_soundex_match(self):
        """Phonetic similarity should catch homophones."""
        engine = SimilarityEngine()
        score = engine.similarity("night", "nite")
        assert score >= 0.5

    def test_homoglyph_cyrillic_confusables(self):
        engine = SimilarityEngine()
        assert engine.similarity("react", "rеаct") >= 0.95
        assert engine._normalize_homoglyphs("rеаct") == "react"

    def test_homoglyph_mixed_scripts_and_fullwidth_digits(self):
        engine = SimilarityEngine()
        assert engine.similarity("paypal", "pаypal") == 1.0
        assert engine.similarity("pkg123", "pkg１２３") == 1.0

    def test_homoglyph_ascii_behavior_is_unchanged(self):
        engine = SimilarityEngine()
        assert engine._normalize_homoglyphs("React") == "react"
        assert engine._homoglyph_similarity("abc", "xyz") == 0.0

    def test_levenshtein_distance(self):
        """Levenshtein distance between 'kitten' and 'sitting' is 3."""
        engine = SimilarityEngine()
        dist = engine.levenshtein("kitten", "sitting")
        assert dist == 3

    def test_levenshtein_identical(self):
        engine = SimilarityEngine()
        dist = engine.levenshtein("hello", "hello")
        assert dist == 0


# ── Known Packages DB Tests ────────────────────────────────────────

class TestKnownPackagesDB:
    """Database of known legitimate packages."""

    def test_load_builtin_db(self):
        """Built-in database loads with top packages."""
        db = KnownPackagesDB()
        assert db.is_known("serde")
        assert db.is_known("tokio")
        assert db.is_known("clap")
        assert db.is_known("react", ecosystem="node")
        assert db.is_known("lodash", ecosystem="node")
        assert db.is_known("requests", ecosystem="python")

    def test_unknown_package(self):
        """Packages not in DB return False."""
        db = KnownPackagesDB()
        assert not db.is_known("zzz-nonexistent-zzz-12345")

    def test_get_similar_known(self):
        """Find similar known packages for a given name."""
        db = KnownPackagesDB()
        similar = db.get_similar("proc-macro1", threshold=0.8)
        # Should find proc-macro2 as similar
        names = [name for name, score in similar]
        assert any("proc-macro" in n for n in names)

    def test_get_similar_empty_for_unique(self):
        """Unique names return empty similar list."""
        db = KnownPackagesDB()
        similar = db.get_similar("zzzz-unique-name-zzzz", threshold=0.8)
        assert len(similar) == 0

    def test_case_sensitive_ecosystem_exact_match(self):
        """Case-sensitive ecosystems (go) do not fold case."""
        db = KnownPackagesDB()
        assert db.is_known("gin", ecosystem="go")
        assert not db.is_known("Gin", ecosystem="go")

    def test_get_similar_case_sensitive_ecosystem(self):
        """get_similar does not fold case for case-sensitive ecosystems (go)."""
        db = KnownPackagesDB()
        similar = db.get_similar("Gin", threshold=0.8, ecosystem="go")
        names = [name for name, _ in similar]
        assert "gin" not in names

    def test_case_insensitive_ecosystem_folded_match(self):
        """Case-insensitive ecosystems (node) fold case."""
        db = KnownPackagesDB()
        assert db.is_known("Lodash", ecosystem="node")

    def test_precomputed_lowered_set_exists(self):
        """The lowered-name sets are precomputed once at construction."""
        db = KnownPackagesDB()
        assert isinstance(db._lowered_packages, dict)
        assert "rust" in db._lowered_packages


# ── Risk Scorer Tests ──────────────────────────────────────────────

class TestRiskScorer:
    """Calculate risk score for dependencies."""

    def test_clean_package_low_risk(self):
        """Well-known packages should be LOW risk."""
        scorer = RiskScorer()
        result = scorer.score("serde")
        assert result.level == RiskLevel.LOW

    def test_typosquat_high_risk(self):
        """Typosquat of known package should be HIGH risk."""
        scorer = RiskScorer()
        result = scorer.score("proc-macro1")
        assert result.level in (RiskLevel.HIGH, RiskLevel.CRITICAL)

    def test_homoglyph_reason_is_reported(self):
        scorer = RiskScorer()
        result = scorer.score("rеаct", ecosystem="node")
        assert result.level == RiskLevel.CRITICAL
        assert "(homoglyph)" in result.reason

    def test_unknown_package_medium_risk(self):
        """Unknown packages should be MEDIUM risk (not known, not typosquat)."""
        scorer = RiskScorer()
        result = scorer.score("zzz-completely-new-package-zzz")
        assert result.level == RiskLevel.MEDIUM

    def test_score_includes_similar_packages(self):
        """Result should list similar known packages."""
        scorer = RiskScorer()
        result = scorer.score("proc-macro1")
        assert len(result.similar_packages) > 0

    def test_risk_level_ordering(self):
        """Risk levels should be comparable."""
        assert RiskLevel.LOW.value < RiskLevel.MEDIUM.value
        assert RiskLevel.MEDIUM.value < RiskLevel.HIGH.value
        assert RiskLevel.HIGH.value < RiskLevel.CRITICAL.value


# ── Integration Tests ──────────────────────────────────────────────

class TestIntegration:
    """End-to-end typosquat detection."""

    def test_detect_proc_macro1_attack(self, tmp_path):
        """Detects proc-macro1 as typosquat of proc-macro2."""
        cargo_lock = tmp_path / "Cargo.lock"
        cargo_lock.write_text("""version = 3

[[package]]
name = "serde"
version = "1.0.204"

[[package]]
name = "proc-macro1"
version = "1.0.107"
""")
        from taintrace.detector import TyposquatDetector
        detector = TyposquatDetector()
        results = detector.scan(cargo_lock)
        
        # Should flag proc-macro1 as suspicious
        suspicious = [r for r in results if r.is_suspect]
        assert len(suspicious) >= 1
        assert any("proc-macro1" in r.dependency.name for r in suspicious)

    def test_clean_deps_no_alerts(self, tmp_path):
        """Clean dependencies should produce no suspicious results."""
        cargo_lock = tmp_path / "Cargo.lock"
        cargo_lock.write_text("""version = 3

[[package]]
name = "serde"
version = "1.0.204"

[[package]]
name = "tokio"
version = "1.38.0"

[[package]]
name = "clap"
version = "4.5.0"
""")
        from taintrace.detector import TyposquatDetector
        detector = TyposquatDetector()
        results = detector.scan(cargo_lock)
        suspicious = [r for r in results if r.is_suspect]
        assert len(suspicious) == 0


def test_detector_similarity_threshold_controls_matches(monkeypatch):
    from taintrace.detector import TyposquatDetector
    detector = TyposquatDetector(ecosystem="node", similarity_threshold=0.83)
    seen = {}
    original = detector.db.get_similar

    def capture(name, threshold=0.8, ecosystem=None):
        seen["threshold"] = threshold
        return original(name, threshold=threshold, ecosystem=ecosystem)

    monkeypatch.setattr(detector.db, "get_similar", capture)
    detector.scan_dependency("lodas", ecosystem="node")
    assert seen["threshold"] == 0.83


def test_detection_result_reports_similarity_scores():
    from taintrace.detector import TyposquatDetector
    result = TyposquatDetector(ecosystem="node", similarity_threshold=0.7).scan_dependency(
        "lodas", ecosystem="node"
    )
    assert result.similarity_scores
    name, score = result.similarity_scores[0]
    assert isinstance(name, str)
    assert 0.7 <= score <= 1.0


def test_json_report_includes_match_similarity_scores(tmp_path):
    import json
    from click.testing import CliRunner
    from taintrace.cli import cli

    lockfile = tmp_path / "Cargo.lock"
    lockfile.write_text('[[package]]\nname = "proc-macro1"\nversion = "1.0.0"\n')
    result = CliRunner().invoke(cli, ["check", str(lockfile), "--format", "json", "--threshold", "0.7"])
    payload = json.loads(result.output)
    item = payload["results"][0]
    assert item["similarity_scores"]
    assert item["similarity_scores"][0]["package"]
    assert 0.7 <= item["similarity_scores"][0]["score"] <= 1.0


def test_cli_rejects_similarity_threshold_outside_range(tmp_path):
    from click.testing import CliRunner
    from taintrace.cli import cli

    lockfile = tmp_path / "requirements.txt"
    lockfile.write_text("requests==2.32.3\n")
    result = CliRunner().invoke(cli, ["check", str(lockfile), "--threshold", "1.1"])
    assert result.exit_code == 2
    assert "not in the range" in result.output
